# Generated by Django 5.2.8 on 2025-11-20 11:35

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='class_name_i18n',
            field=models.JSONField(blank=True, default=accounts.models.default_i18n),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='college_i18n',
            field=models.JSONField(blank=True, default=accounts.models.default_i18n),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender_i18n',
            field=models.JSONField(blank=True, default=accounts.models.default_i18n),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='major_i18n',
            field=models.JSONField(blank=True, default=accounts.models.default_i18n),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
