# Generated by Django 5.2.8 on 2025-11-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_course_end_time_remove_course_last_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
