# Generated by Django 5.2.8 on 2025-11-27 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_unique_first_week_monday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('gender', models.CharField(blank=True, max_length=16)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('position_category', models.CharField(blank=True, max_length=120)),
                ('title_level', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('staff_category', models.CharField(blank=True, max_length=120)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('name_i18n', models.JSONField(blank=True, default=dict, help_text="Name in different languages {'zh': '', 'en': ''}")),
                ('department_i18n', models.JSONField(blank=True, default=dict, help_text="Department in different languages {'zh': '', 'en': ''}")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunSQL(
            "UPDATE accounts_course SET teacher = NULL",
            reverse_sql="SELECT 1"  # No reverse needed
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='accounts.facultyprofile'),
        ),
    ]
