# Generated by Django 5.2.8 on 2025-11-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_facultyprofile_alter_course_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_type',
            new_name='course_type_detail',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='first_week_monday',
            new_name='term_start_date',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='week_pattern',
            new_name='weeks',
        ),
        migrations.RenameField(
            model_name='facultyprofile',
            old_name='position_category',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='facultyprofile',
            old_name='staff_category',
            new_name='staff_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='department_i18n',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='name_i18n',
        ),
        migrations.AddField(
            model_name='course',
            name='audience',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='campus_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='course',
            name='class_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='course',
            name='department_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='course',
            name='enrolled_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='exam_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='course',
            name='grades',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='course',
            name='grading_method',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='course',
            name='hours_per_week',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='course',
            name='majors',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='nature',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='course',
            name='teaching_mode',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='course',
            name='total_course_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='weekday',
            field=models.SmallIntegerField(default=-1, help_text='-1 = unscheduled, 1 = Monday, 7 = Sunday'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='is_main_lecturer',
            field=models.BooleanField(default=False),
        ),
    ]
