# Generated by Django 5.2.8 on 2025-11-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_course_type_course_course_type_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(default=0, help_text='Maximum number of students that can enroll in this course'),
        ),
    ]
