# Generated by Django 5.2.8 on 2025-11-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_course_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitypreference',
            name='force_faculty_change_default',
            field=models.BooleanField(default=False),
        ),
    ]
