# Generated by Django 5.2.8 on 2025-11-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_description_i18n_activity_title_i18n_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='college_required',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
